author: matt@sivel.net
filesets:
    includes:
        - README.md
        - LICENSE
    excludes:
        - \.git
settings:
    build: |
        go get github.com/GeertJohan/go.rice && go get github.com/GeertJohan/go.rice/rice && rice embed-go && go build
    outfiles:
        - spinclass
